services:
  app:
    build:
      context: node
      target: development
    image: alissonmartineli/node:development
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    container_name: app
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true

  db:
    image: mysql:5.7
    container_name: db
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
